### ISSUE TITLE
چطوری می تونم تاریخ های قبلی رو غیر فعال کنم

### ISSUE THREAD

**Issue by hosseinhashemi** [behzadi/persianDatepicker#1]
من یه سوالی داشتم چطوری می تونم تاریخ های قبلی رو غیر فعال کنم
برای مثال کاربر فقط تاریخ های آتی رو بتونه گزینش بکنه
و این به این خاطر هست که من دارم یک سیستم رزرو آنلاین تهیه می کنم و خب منطقی نیست که کاربر بتونه تاریخ های گذشته رو انتخاب بکنه
من option های زیر رو دیدم
selectableYears: null,
    selectableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
​اما نمی دونم چجوری config کنم که خواسته ام مرتفع بشه چون باید داینامیک باشه ​و نمی تونم ماه های خاصی رو غیر فعال کنم

ممنون و سپاس

**Comment by behzadi** [comment]
سلام ایشالا تو هفته آینده این امکان اضافه میشه..

**Comment by setarbgram** [comment]
سلام این امکان رو کجا میتونم پیدا کنم؟ اگه اضافه شده. ممنون

**Comment by behzadi** [comment]
سلام 
لینک زیر را مشاهده بفر مایید
startDate & endDate 

[http://behzadi.github.io/persianDatepicker/#workWithPersianDate](http://behzadi.github.io/persianDatepicker/#workWithPersianDate)
