### ISSUE TITLE
Using with angular.js

### ISSUE THREAD

**Issue by La-Volpe** [behzadi/persianDatepicker#11]
We need the date to be sent to our services via angular.js . thus, I've given the <input> tag of our calendar, the data-ng-model="theDate". but when I want to access it in our Angular file, by saying for example: 
    console.log($scope.theDate);
It returns a null string. Even though we've already entered a date (picked, using the picker).
do we miss something? when I use the same method on my other <input> tags, the result is OK, as expected! i.e: <input data-ng-model="test"> and then I put the value "Hi" inside it, 
    console.log($scope.test);
returns "Hi".
I really don't know where to look for the problem.

**Comment by raysmithdev** [comment]
Is the date being displayed in a select box?

**Comment by behzadi** [comment]
it's work with angularjs..
