### ISSUE TITLE
نمایش خارج از صفحه نمایش

### ISSUE THREAD

**Issue by javansolo** [behzadi/persianDatepicker#12]
با سلام
در هنگامی که input
در پایین صفحه می باشد نیاز است که صفحه اسکرول نخورد و به صورت آتوماتیک از قابلیتهایی مثل این پلاگین :
http://tlindig.github.io/position-calculator/
استفاه شود
لطف کنید و این قابلیت رو اضافه کنید
متشکر

**Comment by behzadi** [comment]
درود، تا الان ندیده بودم تو انتخاب کننده ها این امکان باشه و فکر بسیار خوبیه بر روی عملی شدن این موضوع کار کرده ونتیجه را اعلام میکنم 

سپاس فراوان

**Comment by javansolo** [comment]
خطوط 180 و 181 رو جابه جا کن تا لااقل بشه بعد از نمایش مقعیش رو تغییر داد
بعد از جابه جایی این خطوط کار تغییر پوزیشن در تابع
onShow
به درستی انجام می گیرد ولی قبل از این تغییر چون شما بعد از صدازدن
onShow
تابع
onresize
را صدا می زنید تغییر مقعیت بی فایده است.
متشکر
