### ISSUE TITLE
hide on blur

### ISSUE THREAD

**Issue by hos69shah** [behzadi/persianDatepicker#13]
Is that possible to hide the calendar when the input button loose focus??
Currently it will disappear if and only if you select a date.

**Comment by behzadi** [comment]
بله با جی کوئری امکان پذیر هست

2015-08-16 15:10 GMT+04:30 hos69shah <notifications@github.com>:

> سلام امکان مخفی کردن انتخاب تاریخ وقتی که فوکوس از اینپوت برداشته میشه
> هست؟؟
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/behzadi/persianDatepicker/issues/13>.
>



-- 

*Yours truly Behzadi*

**Comment by behzadi** [comment]
This option will be added..

**Comment by behzadi** [comment]
#### دوست عزیز این امکان اضافه شد

```javascript
closeOnBlur: true
```
پیش فرض بسته می شود

موفق باشید

**Comment by hos69shah** [comment]
تشکر از لطفتون
