### ISSUE TITLE
عدم نمایش تقویم

### ISSUE THREAD

**Issue by MansoorJafari** [behzadi/persianDatepicker#14]
سلام 
زمانی که فایل را داخل پیج لود میکنم 
با Insepct گرفتن مشخص میشه  
datepicker  رو نمیشناسه.
ممنون میشم راهنمایی کنید.

**Comment by behzadi** [comment]
####سلام این خطا معمولا برای اینه که جی کوری رو به درستی لود نکردید:
<link href="default.css" />   
<script src="jquery.js" ></script>
<script src="persianDatepicker.js" ></script>
<script>
```javascript
$("#elementId").persianDatepicker();
```
</script>
ترتیب قرار گیری مهمه

**Comment by MansoorJafari** [comment]
خیلی ممنونم مشکل حل شد.
کاش این قابلیت رو داشت که زمانی که 
datepicker 
باز هست هر جای صفحه کلیک کنیم بسته بشه.

بازم ممنونم.

**Comment by behzadi** [comment]
#### دوست عزیز این امکان در قالب یک آپشن به تقویم اضافه شد
موفق باشید
