### ISSUE TITLE
بازه تاریخی

### ISSUE THREAD

**Issue by omidkh68** [behzadi/persianDatepicker#15]
سلام
ممنون بابت این پلاگین عالی خیلی وقته داریم ازش استفاده میکنیم
فقط تنها امکانی که خیلی خوبه اضافه بشه و ما دنبالش هستیم اینه که بشه بازه انتخاب کرد و مثلا اون بازه رو غیر فعال کرد و فعال کرد
آیا برنامه ای برای این امکان دارید؟

**Comment by behzadi** [comment]
#####با سلام امکانی هست که میتوان فقط در یک بازه تاریخ را انتخاب کرد، نمونه زیر را ببینید:

http://behzadi.github.io/persianDatepicker/#startDate

######با تشکر
