### ISSUE TITLE
z-Index Issue

### ISSUE THREAD

**Issue by deadmann** [behzadi/persianDatepicker#16]
توی این جز z-Index کار نمی کند، و در صورت ست شدن به صورت دستی یا غیر دستی، خود جز به سرعت این مقدار را حذف می کند.

خواهشا این مورد را Fix  کنید. و همچنین به Config جز نیز اضافه نمایید.

**Comment by behzadi** [comment]
### با سلام این مورد برطرف شد
### با تشکر
