### ISSUE TITLE
افزودن پشتیبانی از angular

### ISSUE THREAD

**Issue by captainhamid** [behzadi/persianDatepicker#17]
سلام
خیلی وقته که از این کتابخونه استفاده میکنم.
اگه پیشتیبانی از آنگولار هم بگذارید خیلی خوبه.
ممنون

**Comment by behzadi** [comment]
# با سلام
نحوه استفاده با انگولار را در لینک زیر ببینید:
http://behzadi.github.io/persianDatepicker/WithAngular.html

ممنون از نظرتون

**Comment by captainhamid** [comment]
ضمن تشکر از پاسخ شما یکی از دوستان این رو به صورت دایرکتیو تعریف کرده میگذارم که بقیه شاید به دردشون بخوره
    app.directive('persianCallender', function () {
        return {
            restrict: 'A',
            require: 'ngModel',
            priority: 1,
            link: function (scope, element, attr, ngModelCtrl) {
                $(element).persianDatepicker();
                if (attr.type === 'radio' || attr.type === 'checkbox') return;
                $(document).click(function (e) {
										console.log("clicl", e.target);
                    if ($(e.target).is("div.day.cell.selday")) {
                        scope.$apply(function () {
                            ngModelCtrl.$setViewValue(element.val());
                        });
                    }
                });
                element.bind('blur input keydown change focus', function () {
                    scope.$apply(function () {
                        ngModelCtrl.$setViewValue(element.val());
                    });
                });
            }
        };
    });
و روش استفاده
<input type="text"  persian-calender>
