### ISSUE TITLE
Leaking global variables

### ISSUE THREAD

**Issue by zumoshi** [behzadi/persianDatepicker#18]
salam ,
variable global `b` bad az ejraye tabe persian datepicker avaz mishe , scope in variable dorost tarif nashode
![image](https://cloud.githubusercontent.com/assets/4184939/12750080/ff779672-c9c9-11e5-8046-8641f7132454.png)

**Comment by behzadi** [comment]
### salam, ehtemalan bara ye library dige hast!

![dddd](https://cloud.githubusercontent.com/assets/6107796/16105280/2288341c-339e-11e6-81ef-34db6e4a64fc.JPG)
