### ISSUE TITLE
Persian number in the input field

### ISSUE THREAD

**Issue by stylishweb** [behzadi/persianDatepicker#19]
Not sure if this would be considered a bug, but It would be nice to see Persian numbers in the actual input field as opposed to Latin...

Many thanks

**Comment by behzadi** [comment]
Hi, the numbers in the input field, should be  Latin numbers.. because Latin numbers is better for many operations  (like convert date to Gregorian date, compare tow date, etc)

Thanks a lot ..

**Comment by bndghn** [comment]
I think its better that developer decides which work is better. for converting or other operation developer can use other hidden input. Persian number can help to have pretty form.
