### ISSUE TITLE
How to add image icone beside text fields 

### ISSUE THREAD

**Issue by nimat-netlinks** [behzadi/persianDatepicker#21]
Dear Behzadi,

How to add image icone beside text fields for example :

$(function() {
    $( "#datepicker" ).persianDatepicker({
      showOn: "button",
      buttonImage: "images/calendar.gif",
      buttonImageOnly: true,
      buttonText: "Select date"
    });
  });

**Comment by behzadi** [comment]
### Hi , this option not available for now, but you can create this with css and jQuery.
 ### Many Thanks
