### ISSUE TITLE
چند مشکل در پلاگین

### ISSUE THREAD

**Issue by wp-src** [behzadi/persianDatepicker#22]
سلام. من برای پروژه ام پلاگینتونو استفاده کردم. اما دو مشکل داشت که یکی باگ بود و دومی سلیقه ای که فکر کنم بهتر باشه بهش اضافه کنید این قابلیت رو.
اول اینکه وقتی بازه زمانی برای پلاگین تعریف می کنیم استارت دیت و اند دیت دکمه هم اکنون از کار میوفته!
که این مورد رو با حذف شرط زیر برطرف کردم:
if (self.options.startDate == null)
خط 439

و مورد دوم اینکه باز هم وقتی بازه زمانی اضافه می کنیم نمیشه seleected date رو روی today گذاشت.
عبارت today توی اونجا جواب نمیده و من برای رفع این مورد توی خط 84 گفتم مثل today قرار بده مقدارشو یعنی now
و چون شرط سلکت دیت بعد از این شرط هست اگر سلکتد دیت هم کاربر تعریف کنه باز هم مشکلی نیست.

تشکر بابت پلاگین خوبتون.

**Comment by behzadi** [comment]
### درود ، این دو مورد عمدا گذاشته شده و درسته، سلیقه ای هست.. فرض بفرمایید یکی بازه تاریخ رو برای یک ماه بعد تعیین کنه .. پس قانونا نباید بتونه امروز رو انتخاب کنه

### با تشکر

**Comment by wp-src** [comment]
سلام. اها خوب این قضیه رو باز هم نباید بگید اگر startDate نال بود باید بگید اگر از امروز بزرگتر بود.
یا اینکه این مشکل رو به روش دیگه ای حل کنید. چون الان توی سناریوی من شبیه باگ عمل میکرد. چون می خواستم که استارت 1300 و انتها امروز باشه ولی توی این حالت دکمه امروز کار نمیکرد.

غیر از این مشکلات وقتی تاریخ رو کلیک می کنیم اون قسمت هم درست اسکرول نمیکرد به تاریخ انتخاب شده. اگر بتونید اون رو هم مشکلش رو برطرف کنید که دقیقا بره به امروز خیلی خوب میشه. من یکمی سعی کردم با محاسبه کاری کنم به تاریخی که فعال هست اسکرول کنه، اما خیلی جالب نبود.
موفق باشید.
