### ISSUE TITLE
نمایش روزها در تقویم 

### ISSUE THREAD

**Issue by SepidehIzadi** [behzadi/persianDatepicker#23]
سلام و تشکر بابت پلاگین خوبتون
من یه مشکلی دارم که نمیدونم باید چطوری حلش کنم. اگه به من کمک کنید خیلی ممنون میشم.
من یه مقدار پلاگین رو برای خودم سفارشی کردم و می تونم چند روز رو توی تقویم انتخاب کنم و توی یک آرایه نگه میدارم و در نهایت پس از یکسری عملیات روزهایی رو که انتخاب کردم توی دیتابیس ذخیره می کنم. حالا مشکل اینجاست که من وقتی دارم تقویم رو نمایش میدم بعد از لود فرم و داکیومنت ردی کاربر باید بتونه با انتخاب یک آیتم از دراپ دان روزهایی رو که به ازای اون آیتم توی دیتابیس ذخیره شده رو ببینه. 
قبلا برای روزهای ذخیره شده در تقویم یک سی اس اس اضافه کردم.
حالا مشکل اینجاست که من نمی تونم این روزها رو به کاربر نمایش بدم. اگر برای حل مشکل بهم کمک کنید از شما بسیار ممنون میشم.

**Comment by behzadi** [comment]
##### سلام ممنونم
#####  لطفا نمونه کدتون رو یه جایی  آنلاین بزارین ببینم
https://jsfiddle.net/behzadi/ut3ntog6/

**Comment by SepidehIzadi** [comment]
فکر میکنم منظورم رو واضح ننوشته بودم: ما با استفاده از ایجکس یک آرایه که شامل چند تاریخ مختلف است را از سرور دریافت می کنیم ، حالا می خوایم تاریخ های درون این آرایه را روی تقویم شما با یک رنگ متمایز نمایش دهیم.

امیدوارم این توضیحات بیشتر کمک کنه.

**Comment by behzadi** [comment]
با سلام
لینک زیر را ببینید
تاریخ بصورت 1395/5/9 بدون صفر مقایسه میشه
https://jsfiddle.net/behzadi/p9vLyajo/

**Comment by SepidehIzadi** [comment]
سلام مرسی ، این کار می کنه 
از لطفتون بسیار سپاسگزارم
