### ISSUE TITLE
tags added to page per new 

### ISSUE THREAD

**Issue by masoodinfo** [behzadi/persianDatepicker#27]
سلام .خیلی خوشحالم که ایرانی ها هم آره !!!
ممنون از این کامپوننت
فقط مشکلی که هست اینه که وقتی نیو میکنیم تگ های اچ تی ام ال به انتهای بادی اضافه میشه و در نیو های پیاپی مشکل رم پیش میاد
اما دیتاپیکر خارجکی یه بار تگ های مورد نیازشو میسازه و در هر بار استفاده ازهمون تگ ها استفاده میکنه

**Comment by behzadi** [comment]
## با سلام
## سپاس 
## انتخاب کننده یک بار بیشتر کد اچ تی ام ال نمیسازه و هربار همون رو فراخوانی می کنه
## موفق باشید
