### ISSUE TITLE
تبدیل تاریخ

### ISSUE THREAD

**Issue by mehrdadch** [behzadi/persianDatepicker#28]
آیا افزونه شما میتواند تاریخ پارسی رو به میلادی تبدیل کند و وارونه آن هم

**Comment by behzadi** [comment]
[http://behzadi.github.io/persianDatepicker/#convertDates](url)

**Comment by mehrdadch** [comment]
پیوند شما خطا 404 می دهد

**Comment by behzadi** [comment]
it's strange! but:
http://behzadi.github.io/persianDatepicker/#convertDates

**Comment by mehrdadch** [comment]
آیا می توان تاریخ میلادی رو داد و تاریخ پارسی دریافت کرد مثال شما تنها تبدیل تاریخ پارسی به میلادی است

**Comment by behzadi** [comment]
بله، توابعش کامل هست
