### ISSUE TITLE
مشکل در عنوان تابع

### ISSUE THREAD

**Issue by kiansite** [behzadi/persianDatepicker#3]
سلام
لطفا در مستندات قسمت زیر را اصلاح نمایید.

	 
	        $("#birthDate, #shProvinceId").persianDatePicker();       
	    
	
در عبارت بالا Picker
با حرفP
بزرگ تایپ شده که در اصل باید کوچک باشد
ممنون از برنامه خوبتون.

**Comment by javansolo** [comment]
سلام
لطفا در مستندات قسمت زیر را اسلاح کنید:
$("#input1")persianDatePicker
که نقطه بعد از پرانتز جا افتاده است
منون

**Comment by behzadi** [comment]
hi , solved thanks..
