### ISSUE TITLE
Daterange picker

### ISSUE THREAD

**Issue by information-security** [behzadi/persianDatepicker#30]
Hi,

How can I use this library as a daterange picker (same as http://www.daterangepicker.com)? Is it implemented or do you have a plan to implement it anytime soon? I think that will add an extra value to your current excellent library.

Regards

**Comment by skmohammadi** [comment]
سلام.

برای انتخاب تاریخ به صورت #شروع و #پایان دچار مشکل هستم.

دو تا ورودی دارم یکی برای ابتدای بازه یکی برای انتهای بازه.

وقتی مقدار
startDate
رو تنظیم میکنم و مقدار
endDate
رو تنظیم نمیکنم، خطا دریافت میکنم.

چطور میشه فقط مقدار شروع رو تنظیم کرد و نیازی به مقدار پایان نباشه.

**Comment by behzadi** [comment]
با سلام
درحال حاضر تنها با وارد کردن هردو بازه امکان پذیره 
اما در آپدیت های بعدی این مشکل را بررسی میکنم
