### ISSUE TITLE
مشکل با ریست کردن

### ISSUE THREAD

**Issue by amin750** [behzadi/persianDatepicker#31]
برای ریست کردن متدی وجود ندارد

**Comment by FarshadKazemi** [comment]
درود

من برای این کار با
 z-index 
مربوط به
 div  
ساخته شده کار کردم و جواب داد (یعنی در حال حاضر مشکلم رو حل کرده)

برای غیر فعال کردن
$('.pdp-default').css({'z-index': -1})

فعال سازی
$('.pdp-default').css({'z-index': 'auto'})
$(mySelector).persianDatepicker();

من از تم پیشفرض اسفاده کردم، بنابراین کلاسی که سلکت میکنم
pdp-default
هستش

**Comment by behzadi** [comment]
درود
با دستورات jQuery میشه یه پلاگین رو ریست کرد
