### ISSUE TITLE
نبود جمله <!DOCTYPE html> در اول صفخات

### ISSUE THREAD

**Issue by sabbaghi89** [behzadi/persianDatepicker#33]
فکر کنم این مشکل باشه که حتما باید اول صفحات HTML جمله <!DOCTYPE html> وجود داشته باشه تا سیستم دیت پیک درست عمل کنه. امتحان کنین متوجه میشین.

**Comment by behzadi** [comment]
سلام
بله این عبارت به مرورگر می فهمونه که چه نسخه ای از اچ تی ام ال قراره لود بشه
حتما تو تمام صفحات قرار بدید
