### ISSUE TITLE
view mode

### ISSUE THREAD

**Issue by bndghn** [behzadi/persianDatepicker#36]
HI.
please add view mode to datapicker options. the values can year, month and day.
for select born date, best view mode is years!

**Comment by behzadi** [comment]
Hi, I did not understand what you mean

**Comment by bndghn** [comment]
I want when user need enter botn date, first select years, second moon then day.
in this case, user when click in input, datapicker at fist show years, after select years, show moon. at end show day

**Comment by behzadi** [comment]
this option is not implemented yet..
i'm thinking about it
thanks
