### ISSUE TITLE
خطا بعد از فراخوانی دوباره صفحه

### ISSUE THREAD

**Issue by bndghn** [behzadi/persianDatepicker#37]
با سلام و عرض ادب
بعد از ارسال دیتا صفحه و برگشت دوباره به همان فرم قبلی، انتخابگر تاریخ دیگر کار نمیکند. 
قابل توجه است که هنگام بارگذاری انتخاب گر تاریخ برای بار اول مشکلی نیست و این مشکلی زمانی رخ میدهد که فرم به سرور ارسال شده و دوباره برای اصلاح محتویات به فرم و ... برمیگردد.

**Comment by behzadi** [comment]
در هنگام بازگشت احتمالا خطای جاوا اسکریپت رخ می دهد
