### ISSUE TITLE
problem with data-jdate and data-gdate

### ISSUE THREAD

**Issue by skmohammadi** [behzadi/persianDatepicker#38]
سلام جناب بهزادی.

متوجه شدم که عملگر
data("gdate"))
یا عملگر
data("jdate"))
پس از اولین فراخوانی مقدارش کش میشه.

یعنی اگر برای اولین بار مقدار تاریخ جلالی
**1396/3/17**
رو انتخاب کنید، معادل
**2017/6/7**
برمیگرده.

حالا اگر دوباره یه تاریخ جلالی دیگه انتخاب کنید بازم همون مقدار میلادی قبلی رو نشون میده. در واقع تغییرات آپدیت نمیشه.

این مسئله در صفحه مستندات این افزونه هم مشخصه

http://behzadi.github.io/persianDatepicker/#dataAttr

**Comment by behzadi** [comment]
&#x202b;با سلام و تشکر بابت توجهتون
&#x202b;من خودم نفهمیدم این جزء تغییرات مرورگر هستش یانه، یا این حال باید اینجوری تغییرش بدم که هر روزی برای خودش دیتا میلادی و شمسی را داره برای تغییرات آنی باید از دستور زیر استفاده کنیم
alert($("#pdp-data-jdate").attr("data-gdate")); // attr
&#x202b;با این حال  برا  روزهای ثابت دیتا رو میشه استفاده کرد

[http://api.jquery.com/data/#data-html5](url)
