### ISSUE TITLE
set value input problem

### ISSUE THREAD

**Issue by amir-yeketaz** [behzadi/persianDatepicker#4]
hi ... thanx for your plugin ... 
i am test lots of perisan date picker but your plugin is good ! i like it :) 

but there is bad problem i have seen on it! 
the problem is that when the date is selected it's not set the value input ! 

please solve it !

**Comment by sagho0or** [comment]
thanx for your plugin .but I have this problem too . i used select event but it dident solve! please hepl me .

**Comment by behzadi** [comment]
please show me your code..

**Comment by sagho0or** [comment]
$( ".publish" ).persianDatepicker({
                months: ["فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"],
                dowTitle: ["شنبه", "یکشنبه", "دوشنبه", "سه شنبه", "چهارشنبه", "پنج شنبه", "جمعه"],
                shortDowTitle: ["ش", "ی", "د", "س", "چ", "پ", "ج"],
                showGregorianDate: false,
                persianNumbers: true,
                formatDate: "YYYY/MM/DD",
                prevArrow: '&#10095;',
                nextArrow: '&#10094;',
                theme: 'default',
                alwaysShow: false,
                selectableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                cellWidth: 35, 
                cellHeight: 30, 
                fontSize: 13,             
                isRTL: false,
                calendarPosition: {
                    x: 0,
                    y: 0,
                },
                onShow: function(calendar) {
                    calendar.show();
                },
                onHide: function(calendar) {
                    calendar.hide(function(){
                    });
                },
                onSelect: function(){
                  var date = $('.pdp-el').val()
                  // console.log(date) return '' ; 
                   $scope.newsFrom.date = date;
                }
            }); 

البته لازم هست که توضیح بدم از انگولار استفاده کردم . و روی یک تب مشخص کلیک می کنم و بعد template فراخوانی می شود . در اون زمان کدی که ارسال کردم صدا زده می شود . در قسمت های مشابه دقیقا درست اجرا می شود . اما متاسفانه در این قسمت مقدار خالی برگردانده می شود . مرسی

**Comment by behzadi** [comment]
ok you should:

1- use angular.element($('#newsForm')).scope().setDateVal(); in onSelect function..
2- $scope.date = $(".publish").val(); in your scope function
3- $scope.$apply();  to apply value in your scope.date

for more information please see the  [DEMO](http://behzadi.github.io/persianDatepicker/WithAngular.html)

**Comment by sagho0or** [comment]
thanx alot : )
