### ISSUE TITLE
ارسال نشدن  اینپوت به داخل توابع

### ISSUE THREAD

**Issue by mmasomi73** [behzadi/persianDatepicker#43]
اگر خود المنت ها به داخل توابع ارسال بشود،
یعنی اینپوت داخل توابعی مثل 
onSelect
قابل دسترس باشه.

:)

**Comment by behzadi** [comment]
از طریق جی کوئری قابل حل می باشد

**Comment by mehrshaddarzi** [comment]
@behzadi 
ی مثال میزنید من هم این مشکل رو دارم متاسفانه.
داخل صفحه ی من چندین input دارن توسط جاوا اسکریپت ایجاد میشن ولی نیدونم در زمان OnSelect الان کدوم هست
