### ISSUE TITLE
کار نکردن - data-jdate & data-gdate attributes

### ISSUE THREAD

**Issue by Hamidnch** [behzadi/persianDatepicker#46]
سلام
این قسمت فقط دفعه اول که تاریخ رو انتخاب میکنی درست کار نمیکنه:
بعد اون دیگه فقط همون تاریخ اولی رو برمی گردونه.
    $("#pdp-data-jdate").persianDatepicker({
        onSelect: function () {
            alert($("#pdp-data-jdate").data("gdate"));
        }
    });
    $("#pdp-data-gdate").persianDatepicker({
        showGregorianDate: true,
        onSelect: function () {
            alert($("#pdp-data-gdate").data("jdate"));
        }
    });
همیشه یه مقدار ثابت برای تاریخ برمی گردونه.

**Comment by behzadi** [comment]
سلام درسته .. بخاطر تغییرات مرورگرها است
میتوانید از attr("data-jdate")  ,  attr("data-gdate") استفاده نمایید
