### ISSUE TITLE
مشکل در انتخاب تاریخ به صورت رنج

### ISSUE THREAD

**Issue by mramirghafari** [behzadi/persianDatepicker#47]
سلام وقت بخیر
من میخوام دو تا دیت پیکر کنار هم داشته باشم به صورتی که اولی تاریخ شروع باشه دومی تاریخ پایان
اما میخام تاریخ پایان رو نتونه از تاریخ شروع کمتر بزنه کاربر
یعنی یه چیزی تو این مایه ها:

` startDate: $("#shoro").val(),`

یعنی برای تاریخ پایان نتونه از تاریخ شروع کمتر انتخاب کنه

اما مسئله ای که هست اینه که این پلاگین داره با لود صفحه کال میشه و من نمیتونی تاریخ شروع رو بعد از لود صفحه بفرستم برای این مقدار startdate

ممنون میشم راهنمایی کنید چجوری میتونم همچین کاری بکنم

**Comment by behzadi** [comment]
با سلام 
یه آپشن هست به اسم
onSelect
همچنین از persianDate هم میتونید استفاده کنید

```
onSelect: function(){
      var p = new persianDate();
      $("#payan").persianDatepicker({ startDate: $("#shoro").val(), endDate:p.now().addYear(1);  });
}
```
که میتونید تقویم دوم رو اونجا فراخوانی کنید
