### ISSUE TITLE
عدم تعویض تاریخ در رویداد OnSelect

### ISSUE THREAD

**Issue by kitcat2014** [behzadi/persianDatepicker#53]
سلام
مثال - data-jdate & data-gdate attributes که خودتون گذاشتین رو تست کنین
اول یه تاریخ رو انتخاب کنین
بعد تغییرش بدین
کماکان تاریخ اولی رو بر می گردونه
شما برای رفع ایرادات پاسخ هیچکس رو ندادین
فکر کنم استفاده از ابزار شما به دلیل عدم وجود پشتیبانی فنی اشتباه باشه
با تشکر

**Comment by behzadi** [comment]
سلام 
[https://stackoverflow.com/questions/8707226/jquery-data-does-not-work-but-attr-does](url)
می بایست از attr استفاده کرد
با عرض پوزش که در صفحه تست تغییر داده نشده که الان درست شده
ایرادات بقیه هم در حال انجام و پیگیری هست، ولی خب بعضیاش آپشنال هست مثل اضافه کردن تم
با تشکر
