### ISSUE TITLE
به کارگیری داخل modal 

### ISSUE THREAD

**Issue by mehditaran** [behzadi/persianDatepicker#55]
وقتی داخل مدال ازش استفاده میکنم در نمایش تقویم به مشکل میخوره در سی اس اس که توسط لایبرری رندر میشه از تگ  روت(بادی) به عنوان پدر استفاده میکنه و فاصله از بالا رو نسبت به اون میده. میشه داخل سی اس اس تغییرش داد ولی داخل همون صفحه بیرون از مدال هم استفاده میکنم .
اگر راه حلی هست دوستان ممنون میشم راهنمایی فرمایید .

**Comment by mahdi1366** [comment]
سلام وقت بخیر
من هم این مشکل رو دارم اگه تونستین مشکل رو برطرف کنین ممنون میشم راهنمایی کنین
