### ISSUE TITLE
rHow to reset, refresh or remove it from Elements? i need to reinit it!

### ISSUE THREAD

**Issue by javidoweb** [behzadi/persianDatepicker#58]
Hey Behzadi
I have pages that load via Ajax and i need to refresh "persianDatepicker" for new inputs?
Is there a way to remove this and then init ?
I will be grateful

**Comment by behzadi** [comment]
yes is possible with jquery
please google it

**Comment by i3130002** [comment]
Using either .off('click') + .off("focus") or .unbind(), removes the persianDatepicker but you won't be able to add it again.
