### ISSUE TITLE
how can disable a day?

### ISSUE THREAD

**Issue by msadeghyan1996** [behzadi/persianDatepicker#59]
Hi.
***Before*** any things thank you for persianDatepicker. it's perfect jquery libraries for persian calendar.
i need disable every *saturdat-sunday* in calendar and i don't know how i can do it.
line below image : 
![Image of Yaktocat](http://uupload.ir/files/98mi_untitled-2_copy.png)

**Comment by behzadi** [comment]
Hi, Thank You

this is what you want : [http://jsfiddle.net/behzadi/e5kdp962/](url)

`jQuery(document).ready(function($) {

  $("#pdp1").persianDatepicker({
    alwaysShow: !0,
    onRender: function() {
    	$p = $("#" + $("#pdp1").attr("pdp-id"));
      
      $.each( $p.find(".days>div"), function(index, value) {
       $(value).find(":nth-child(1)").addClass("disday").off("click");
      });
    }
  });

});
`
<script async src="//jsfiddle.net/behzadi/e5kdp962/40/embed/"></script>
