### ISSUE TITLE
error in show jalali, select gregorian date 

### ISSUE THREAD

**Issue by kia1349** [behzadi/persianDatepicker#61]
سلام جناب بهزادی
ممنون بابت زحمتی که برای این پلاگین کشیده اید

یه موردی هست که نیاز به اصلاح داره

در حالتی که میخواهیم تاریخ بصورت شمسی نمایش داده بشه و بصورت میلادی انتخاب و درج بشه ، چنانچه فیلد دارای مقداری 
 برابر با یک تاریخ میلادی باشه ، در زمان نمایش صفحه دیت پیکر دقیقا معادل همون تاریخ ولی در حالت شمسی لود میشه
بطور مثال اگر فیلد تاریخ معادل با
2019/3/24
باشد ، تقویم شما معادل 24 خرداد ماه سال 2019 شمسی رو نشون میده و اگر اون تاریخ انتخاب بشه ، محتوای فیلد میلادی به 
2640/6/14
تغییر پیدا میکنه

**Comment by behzadi** [comment]
درود
امکانش هست نمونه آنلاین ببینم ؟
[http://jsfiddle.net](http://jsfiddle.net)

**Comment by kia1349** [comment]
سلام مجدد
بله حتما

http://shop.aryaclub.com/admin/login

user:demo@android.com
pass:admin


در بخش ورود اطلاعات محصولات و کالا ، فیلد تاریخ استفاده شده که میتونید اونجا رو ملاحظه بفرمایید

**Comment by kia1349** [comment]
جناب بهزادی دیدید مشکل رو؟

**Comment by behzadi** [comment]
درود
مشکل برطرف شد میتوانید نسخه جدید را دانلود نمایید
در تاریخ های میلادی نبایست تقویم تاریخی را انتخاب کند

با تشکر از توجه شما

**Comment by kia1349** [comment]
با تشکر و ممنون از حوصله ایی که به خرج میدین
تست میکنم
