### ISSUE TITLE
مشکل در فراخوانی پلاگین

### ISSUE THREAD

**Issue by AmoEsmaeil** [behzadi/persianDatepicker#65]
سلام روز بخیر
در فراخوانی پلاگین مشکل داریم طبق راهنما پیش رفتم ولی مشکل حل نمیشه
jQuery.Deferred exception: $(...).persianDatepicker is not a function
چنین خطایی میده 
یا
TypeError: $(...).persianDatepicker is not a function
ممنون میشم راهنمایی کنید

**Comment by behzadi** [comment]
با سلام
فایل جاوااسکریپت یا جی کوئری بارگزاری نشده
