### ISSUE TITLE
نحوه تنظیم کانستراکتور که نتواند تاریخ اکنون به بعد را انتخاب کند

### ISSUE THREAD

**Issue by AlirezaMadad** [behzadi/persianDatepicker#66]
با سلام و احترام
 بنده یک کانستراکتور به اینصورت طراحی کردم اما باز هم تاریخ های آینده disabled نمی شود 
راهنمایی می فرمایید چطور اینکار را بکنم
منظورم از آینده بزرگتر از now است
`$("#sampleId").persianDatepicker({
endDate = "today";
});`

**Comment by AlirezaMadad** [comment]
می دانم ربطی ندارد اما startDate= "today" هم امتحان کردم نشد

**Comment by shirazhotel** [comment]
hi, you should use startDate & endDate together 
please check this link
[https://jsfiddle.net/behzadi/Lftx2ypb/4/](demo)

**Comment by behzadi** [comment]
### Hi
you should use startDate & endDate together
please check this link

[https://jsfiddle.net/behzadi/Lftx2ypb/4/](https://jsfiddle.net/behzadi/Lftx2ypb/4/)
