### ISSUE TITLE
Fixed error isLeapYear (اصلاح نمایش سال کبیسه)

### ISSUE THREAD

**Issue by NavidAzhirak7s** [behzadi/persianDatepicker#69]
سال 98 به دلیل کبیسه نبودن باید اسفند ماه 29 روز باشد که در کد اشتباه 30 روز نمایش داده میشود که با جایگذاری کد صحیح میتوان این باگ را رفع کرد

 isLeapYear: function (year) {

// درست   
var Result = false;
        year += 621;
        if ((year % 100 == 0 && year % 400 == 0) || (year % 100 != 0 && year % 4 == 0))
            Result = true;
        return Result;

 // مقدار اشتباه
   //var ary = year > 1342 ? [1, 5, 9, 13, 17, 22, 26, 30] : [1, 5, 9, 13, 17, 21, 26, 30];
      //b = year % 33;
      //if (ary._indexOf(b))
      //  return true;
      //return false;
  }

**Comment by azimot** [comment]
@NavidAzhirak7s , @behzadi
مشکلی که گزارش دادید درست است و این ایراد را دارد که سال کبیسه را درست نمایش نمیدهد
ولی منطق کد  درست است تنها ایرادش در کنترل کردن شرط است که به این صورت میشه درستش کرد :


`      if (ary._indexOf(b)>-1)`

و برای ورژن مینیفای شده : 

`function (n){var t=n>1342?[1,5,9,13,17,22,26,30]:[1,5,9,13,17,21,26,30];return(b=n%33,t._indexOf(b)>-1)?!0:!1}`

**Comment by NavidAzhirak7s** [comment]
> @NavidAzhirak7s , @behzadi
> مشکلی که گزارش دادید درست است و این ایراد را دارد که سال کبیسه را درست نمایش نمیدهد
> ولی منطق کد درست است تنها ایرادش در کنترل کردن شرط است که به این صورت میشه درستش کرد :
> 
> > function (year) {
> > var ary = year > 1342 ? [1, 5, 9, 13, 17, 22, 26, 30] : [1, 5, 9, 13, 17, 21, 26, 30];
> > b = year % 33;
> > **if (ary._indexOf(b)>-1)**
> > return true;
> > return false;
> > }
> 
> و برای ورژن مینیفای شده :
> 
> `function (n){var t=n>1342?[1,5,9,13,17,22,26,30]:[1,5,9,13,17,21,26,30];return(b=n%33,t._indexOf(b)>-1)?!0:!1}`

**Comment by NavidAzhirak7s** [comment]
این مشکل هنوزم هم وجود داره در سال 1399 با وجود اینکه سال کبیسه هست ولی مقدار نمایش داده در30 اسفند به صورت 
 0NaN
 هست

**Comment by azimot** [comment]
@NavidAzhirak7s 

<img src="https://cdn1.bbcode0.com/uploads/2021/5/5/fbb179dae85fde7b3bf4868000819326-full.jpg">

دو تای بالا تاریخ های اسفند 98 و 99 است که خود سایت نشون میده و اون ایرادی که گزارش کردی رو داره هنوز

http://behzadi.github.io/persianDatepicker/

دوتای پایینی بعد از اعمال تغییری است که بالاتر ارسال کردم که کبیسه را هم درست نمایش میدهد

**Comment by behzadi** [comment]
Hi
the problem was because of checking indexOf array function result and now it's solved
thanks all
