### ISSUE TITLE
use with bootstrap

### ISSUE THREAD

**Issue by MrMiM** [behzadi/persianDatepicker#7]
Hello.

If we using boostrap in project with this datepicker styles dosen't work correctly.
When using bootstrap:
![with-bootstrap](https://cloud.githubusercontent.com/assets/3888133/3703885/7f43ccc2-140e-11e4-809c-0723fe226cef.jpg)

Without bootstrap:
![without-bootstrap](https://cloud.githubusercontent.com/assets/3888133/3703893/8c8f338a-140e-11e4-99ac-2ddc1d1efe87.jpg)

**Comment by behzadi** [comment]
solved, thanks
