### ISSUE TITLE
Can make it available through nuget?

### ISSUE THREAD

**Issue by Mousavi310** [behzadi/persianDatepicker#8]
I am .Net programmer. .Net programmer use nuget package installer for adding their libraries to their web project. There is some information in their site: https://www.nuget.org/ . For example there is jquery nuget located in https://www.nuget.org/packages/jquery
I will appreciated if you add this capability. Thank you for your great library.

**Comment by behzadi** [comment]
hi you'r welcome thanks..

**Comment by amastaneh** [comment]
+1
