### ISSUE TITLE
عوض کردن به میلادی

### ISSUE THREAD

**Issue by woxman** [behzadi/persianDatepicker#88]
سلام، امکانش هست با یه پارامتر تقویم رو به صورت میلادی هم نشون داد؟؟؟

**Comment by ghader431** [comment]
وقتی سایت دو زبانه باشه باید بتونیم بر اساس زبان انتخابی نوع نمایش تقویم رو تغییر بدیم. به عنوان مثال کاربر انگلیسی زبان ممکنه هیچ آشنایی ای با زبان فارسی نداشته باشه و اینجوری نمایش دادن تقویم فارسی هم به هیچ دردیش نمی خوره و عملا کار گیر میفته. ممنون میشم طبق درخواست آقای بهرامی امکانی اضافه کنید که بشه بین تقویم میلادی و شمسی با تغییر یه آپشن سوییچ کرد.

**Comment by woxman** [comment]
> وقتی سایت دو زبانه باشه باید بتونیم بر اساس زبان انتخابی نوع نمایش تقویم رو تغییر بدیم. به عنوان مثال کاربر انگلیسی زبان ممکنه هیچ آشنایی ای با زبان فارسی نداشته باشه و اینجوری نمایش دادن تقویم فارسی هم به هیچ دردیش نمی خوره و عملا کار گیر میفته. ممنون میشم طبق درخواست آقای بهرامی امکانی اضافه کنید که بشه بین تقویم میلادی و شمسی با تغییر یه آپشن سوییچ کرد.

سلام...من مجبور شدم راه حل رو خودم اوکی کنم و با یه کتابخونه خارجی هم کمک بگیرم.

شما میتونی تو این آدرس ببینی به چ صورت تقویم به ۴ تا زبان اوکی شده
web.deskyar.ir
