### ISSUE TITLE
درخواست داهنمایی.

### ISSUE THREAD

**Issue by fly2development** [behzadi/persianDatepicker#91]
درود دوست من،
من تو وب تازه کارم، یه دیت پیکر روی ویوهام استفاده کردم اما به اندازه کافی خوب نیست،
فایل سی اس اس رو در کانتنت و فایل جی اس رو در پوشه اسکریپت لایه برنامه گذاشتم، 
طبق اطلاعات شما سورس دارم، اینپوت و تگ اسکریپت رو قراار دادم
نمی دونم مشکل کارم کجاست
می شه مراحل اولیه رو بهم بگید، اگر لطف کنید ممنونمت می شه.

**Comment by MehrshadBaradaran** [comment]
سلام دوست عزیز 
لطفا کدتون بفرستین برسی کنیم
