### ISSUE TITLE
اختلاف بین دو تاریخ و نمایش در یک inpt همان لحظه

### ISSUE THREAD

**Issue by saeedsol1** [behzadi/persianDatepicker#93]
با سلام آیا می شود دو تاریخ رو انتخاب کنیم مثلا از تاریخ تا تاریخ  بتونیم اختلاف را به روز یا ساعت و هر زمان را به دست آوریم؟

**Comment by behzadi** [comment]
بلی

**Comment by saeedsol1** [comment]
چگونه

**Comment by saeedsol1** [comment]
How to get the date difference between two jalali date (persianDatepicker) on clicking the second input date picker?
تفاوت دو تاریخ رو چگونه میشه به دست آورد مثلا: 
date1= 1403/06/06 
date2= 1403/06/06  
result: 1 day

date1= 1403/06/06 
date2= 1403/06/07  
result: 2 day
